In [1]:
import random
import pandas as pd
import numpy as np

In [33]:
# df_m - Мультимодальные признаки с catfeat
df_m = pd.DataFrame([['n', 2, np.nan, 0],
                   ['m', 4, 'v', 1],
                   [np.nan, np.nan, 'v', np.nan],
                   ['n', 3, np.nan, 4],
                    [np.nan, 1, 'w', 3],
                     ['m', 2, 'w', 3]],
                  columns=list("ABCD"))
print(df_m)

# Унимодальный признак с catfeat
df_u = pd.DataFrame([[np.nan, 2, np.nan, 'w'],
                   [3, 4, 'n', np.nan],
                   [np.nan, np.nan, 'n', np.nan],
                   [np.nan, 3, np.nan, 'w']],
                  columns=list("ABCD"))

df_u

     A    B    C    D
0    n  2.0  NaN  0.0
1    m  4.0    v  1.0
2  NaN  NaN    v  NaN
3    n  3.0  NaN  4.0
4  NaN  1.0    w  3.0
5    m  2.0    w  3.0

     A    B    C    D
0  NaN  2.0  NaN    w
1  3.0  4.0    n  NaN
2  NaN  NaN    n  NaN
3  NaN  3.0  NaN    w

In [3]:
# Замена на среднее в колонках numfeat
df_m[['B', 'D']].fillna(df_m[['B', 'D']]).mean()

B    2.4
D    2.2
dtype: float64

**fillna - в аргументе только имена столбцов**
mode() возвращает :
   * df['col'].mode() → Series (твой случай с категориальным признаком )
   * df.mode() → DataFrame, где по колонкам собраны все моды

In [155]:
# Замена на mode в колонках Унимодальных catfeat
# df_u = pd.DataFrame([[np.nan, 2, np.nan, 'w'],
#                    [3, 4, 'n', np.nan],
#                    [np.nan, np.nan, 'n', np.nan],
#                    [np.nan, 3, np.nan, 'w']],
#                   columns=list("ABCD"))

df_u = pd.DataFrame([[ np.nan, 'w'],
                   ['n', np.nan],
                   [ 'n', np.nan],
                   [ np.nan, 'w']],
                  columns=list("CD"))

print(df_u, '\n')

cat_col = df_u.select_dtypes(include=['object', 'category'])

# # TODO fillna без цикла
# Замена на mode в колонках Унимодальных catfeat(df_u[cat_col.columns]).mode()
print('в Унимодальных catfeat mode() возвращает df с 1 строкой : \n', df_u[cat_col.columns].fillna(df_u[cat_col.columns]).mode(), '\n')

df_u[cat_col.columns] = df_u[cat_col.columns].fillna(df_u[cat_col.columns]).mode().iloc[0]

df_u

# TODO fillna в цикле
# for  col in cat_col.columns:
#     
#     # 👉  mode() - в каждом цикле возвращает строку с индексом [0]
#     print(df_u[col].fillna(df_u[col]).mode(), '\n')
#     # 👉 Ставим индекс [0] что бы заполнить соответствующей модой
#     df_u[col] = df_u[col].fillna(df_u[col]).mode()[0]


# df_u

     C    D
0  NaN    w
1    n  NaN
2    n  NaN
3  NaN    w

в Унимодальных catfeat mode() возвращает df с 1 строкой :
    C  D
0  n  w

C:\Users\Kirill\AppData\Local\Temp\ipykernel_11024\2849857608.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_u[cat_col.columns] = df_u[cat_col.columns].fillna(df_u[cat_col.columns]).mode().iloc[0]

   C  D
0  n  w
1  n  w
2  n  w
3  n  w

**fillna - в аргументе только имена столбцов**

mode() возвращает :
   * df['col'].mode() → Series (твой случай с категориальным признаком )
   * df.mode() → DataFrame, где по колонкам собраны все моды

In [200]:
# df_m = pd.DataFrame([['n', 2, np.nan, 0],
#                    ['m', 4, 'v', 1],
#                    [np.nan, np.nan, 'v', np.nan],
#                    ['n', 3, np.nan, 4],
#                     [np.nan, 1, 'w', 3],
#                      ['m', 2, 'w', 3]],
#                   columns=list("ABCD"))

df_m = pd.DataFrame([['n',  'p', 0],
                   ['m', 'v', 1],
                   [np.nan,  'v', np.nan],
                   ['n',  np.nan, 4],
                    [np.nan,  'p', 3],
                     ['m', 'w', 3],
                     ['s', np.nan, 3],
                     ['s', 'w', 3]],
                  columns=list("ABC"))

print('Исходый df : \n', df_m, '\n')

# Имена catfeat признаков
cat_col = df_m.select_dtypes(include=['object', 'category']).columns



# TODO на каждую Моду - 1 строка, три Моды - 3 строки
# mode возвращает 3 строки тк в 2-х признаках три Моды
modes = df_m[cat_col].fillna(df_m[cat_col]).mode()
print('в Мультимодальных catfeat mode() возвращает df c 3 строками : \n', modes, '\n')

# 1️⃣ TODO Случайный выбор элемента из Моды для fillna
# cat_elem = modes.sample(1).index[0]
# print('Случайный элемент cat_elem : \n', cat_elem, '\n')

# TODO в Мультимодальном catfeat для заполнения пропусков  выбираем любую mode индексом [0,1,2] в iloc
# df_m[cat_col] = df_m[cat_col].fillna(df_m[cat_col]).mode().iloc[cat_elem]
# print(df_m, '\n')

# 2️⃣ TODO Случайный выбор элемента из Моды для fillna
choice = modes.sample(1).iloc[0]   # берём случайное значение
print('Случайный элемент cat_elem : \n', choice, '\n')

df_m[cat_col] = df_m[cat_col].fillna(choice)
print(df_m, '\n')

Исходый df :
      A    B    C
0    n    p  0.0
1    m    v  1.0
2  NaN    v  NaN
3    n  NaN  4.0
4  NaN    p  3.0
5    m    w  3.0
6    s  NaN  3.0
7    s    w  3.0

в Мультимодальных catfeat mode() возвращает df c 3 строками :
    A  B
0  m  p
1  n  v
2  s  w

Случайный элемент cat_elem :
 A    s
B    w
Name: 2, dtype: object

   A  B    C
0  n  p  0.0
1  m  v  1.0
2  s  v  NaN
3  n  w  4.0
4  s  p  3.0
5  m  w  3.0
6  s  w  3.0
7  s  w  3.0